### ISSUE TITLE
Low quality image at homepage.

### ISSUE THREAD

**Issue by AbubakarKang** [raghavyuva/portfolio#1]
The website looks great and all but your picture (I'm assuming) on the right of the landing page is not of high quality and it gives a bad impression to users. I recommend you to use any of the following websites to enhance the quality of your image.

https://letsenhance.io/
https://www.fotor.com/features/one-tap-enhance
https://www.befunky.com/features/photo-enhancer/
https://www.cutout.pro/photo-enhancer-sharpener-upscale

![download](https://user-images.githubusercontent.com/90056797/157354799-423ae2e9-a2fa-409e-ab0b-d5b300de2e31.jpg)
r

**Comment by AbubakarKang** [comment]
No reply from owner. Closing this.

**Comment by raghavyuva** [comment]
Hey considered.

**Comment by AbubakarKang** [comment]
> Hey considered.

There hasn't been any changes. Do you want me to open a pull request with the changes?
