### ISSUE TITLE
Works' learn more redirection URL is invalid 

### ISSUE THREAD

**Issue by AbubakarKang** [raghavyuva/portfolio#2]
The following URLs do not work:

https://swiftshare.raghavyuva.com/
https://dashboard.raghavyuva.com

![download](https://user-images.githubusercontent.com/90056797/157356566-4e3b8eca-972e-43d6-ae3a-7493c97713a6.jpg)

**Comment by AbubakarKang** [comment]
No reply from owner. Closing this.

**Comment by raghavyuva** [comment]
Yes, working on that:) thanks for noticing it
